import subprocess

from pathlib import Path
from string import Template
from typing import Final

LIFT_TEMPLATE: Final[Template] = Template(""" # Generated by `python3 generate-scie-releases.py`

[lift]
name = "$filename.scie"
platforms = [
    "macos-aarch64",
]

[[lift.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
release = "20251031"
version = "3.11.14"
flavor = "install_only_stripped"
lazy = true

[[lift.files]]
name = "$filename.pex"

[[lift.commands]]
# This selects the `python` binary from within the interpreter distribution (provided above)
exe = "#{cpython:python}"
args = [
    "{$filename.pex}",
]

[lift.commands.env.replace]
# Satisfy the pants_runner.py deprecation warning
SCIE_PANTS_VERSION = "42.42.42"
""")


CURRENT_PATH: Final[Path] = Path(".")

RELEASES_PATH: Final[Path] = CURRENT_PATH / "releases"
RELEASES_PATH.mkdir(exist_ok=True)

TOOLS_PATH = CURRENT_PATH / "tools"
TOOLS_PATH.mkdir(exist_ok=True)

SCIENCE_BINARY: Final[str] = "science-fat-macos-aarch64"

# Download `science` tool
result = subprocess.run(
    f"gh release download --repo a-scie/lift v0.15.1 --clobber --dir {TOOLS_PATH} --pattern '*fat-macos-aarch64*'",
    shell=True, 
    check=True
)
result = subprocess.run(
    f"chmod +x {TOOLS_PATH}/{SCIENCE_BINARY}",
    shell=True, 
    check=True
)

# Enumerate pex releases
result = subprocess.run(
    "gh release list --repo pantsbuild/pants --exclude-drafts --exclude-pre-releases --limit 5 | awk '{print $1}'", 
    shell=True, 
    check=True,
    capture_output=True
)

recent_releases = result.stdout.decode("utf-8").split()
assert len(recent_releases) == 5, f"Length of recent_releases should be 5 -> {recent_releases}"

# Generate lift, download pex, and create scie
for release in recent_releases:
    # Release names are of the form `release_2.29.1` and files are `pants.2.29.1-cp311-darwin_arm64.pex`
    version = release.split("_")[-1]
    version_path = RELEASES_PATH / version
    version_path.mkdir(exist_ok=True)

    lift_path = version_path / "lift.toml"
    lift_path.write_text(LIFT_TEMPLATE.substitute(filename=f"pants.{version}-cp311-darwin_arm64"))

    # TODO: There might be a way to get `science` to download the PEX as well while building, but I haven't checked    
    result = subprocess.run(
        f"gh release download --repo pantsbuild/pants {release} --clobber --dir {version_path} --pattern '*darwin_arm64*'",
        shell=True, 
        check=True
    )

    # Build the scie
    subprocess.run(
        f"../../tools/{SCIENCE_BINARY} lift build ./lift.toml",
        shell=True, 
        check=True,
        cwd=version_path,
    )
